### ISSUE TITLE
Using your qif lib to write qif files

### ISSUE THREAD

**Issue by dgjnpr** [maloquacious/qif#1]
Hey,

I was looking through this repo and it looks like an excellent implementation of the QIF format in go. I'm writing a Go lib to convert CSV files from various banks (Citi and ING at least) into QIF format. Would you mind if I use your code?

Happy to work with you in anyway. I've made a (very) tentative start on my here: https://github.com/dgjnpr/csv2qif

**Comment by mdhender** [comment]
Hi! Please feel free to use what you can. Thanks, Mike.
